/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002113",
        "tertiary-container": "#805000",
        "primary-fixed": "#dee0ff",
        "background": "#f9f9ff",
        "secondary-fixed": "#6ffbbe",
        "tertiary-fixed": "#ffddb8",
        "error": "#ba1a1a",
        "surface": "#f9f9ff",
        "on-tertiary-fixed": "#2a1700",
        "on-surface": "#121c2a",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-container": "#cacfff",
        "secondary": "#006c49",
        "on-error-container": "#93000a",
        "surface-container-highest": "#d9e3f7",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#454652",
        "surface-container": "#e6eeff",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        "primary-fixed-dim": "#bac3ff",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-dim": "#d0daef",
        "tertiary": "#603b00",
        "secondary-fixed-dim": "#4edea3",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ffc988",
        "surface-tint": "#4355b9",
        "inverse-on-surface": "#ebf1ff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-high": "#dee9fd",
        "outline-variant": "#c5c5d4",
        "on-primary-fixed-variant": "#293ca0",
        "surface-container-low": "#eff3ff",
        "primary-container": "#3f51b5",
        "surface-variant": "#d9e3f7",
        "on-secondary-fixed-variant": "#005236",
        "primary": "#24389c",
        "inverse-surface": "#273140",
        "on-tertiary": "#ffffff",
        "outline": "#757684",
        "on-primary-fixed": "#00105c",
        "on-background": "#121c2a",
        "surface-bright": "#f9f9ff",
        "inverse-primary": "#bac3ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px",
        "pill": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "container_padding": "32px",
        "stack_gap": "16px",
        "mobile_margin": "16px",
        "sidebar_width": "280px",
        "topbar_height": "64px"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
